import {Column} from "./Column";

const defaultColumns: Column[] = [                                                    // determines order of columns
    {
        name: 'instrumentName',
        label: 'Market',
        frozen: true,
        hidden: false,
        classes: ['market'],
        id: Math.random(),
        disabled: true,
    },
    {
        name: 'quickTrade',
        label: 'Trade',
        frozen: true,
        hidden: false,
        classes: ['trade'],
        id: Math.random(),
    },
    {
        name: 'changeDay',
        label: 'Change (day)',
        frozen: true,
        hidden: false,
        id: Math.random(),
    },
    {
        name: 'changeWeek',
        label: 'Change (Week)',
        frozen: true,
        hidden: true,
        id: Math.random(),
    },
    {
        name: 'changeMonth',
        label: 'Change (Month)',
        frozen: true,
        hidden: true,
        id: Math.random(),
    },
    {
        name: 'rsi',
        label: 'RSI',
        frozen: false,
        hidden: false,
        classes: ['rsi'],
        id: Math.random(),
    },
    {
        name: 'positions',
        label: 'Positions',
        frozen: false,
        hidden: false,
        id: Math.random(),
    },
    {
        name: 'sparklineDay',
        label: 'Chart (Day)',
        frozen: false,
        hidden: false,
        classes: ['static'],
        id: Math.random(),
    },
    {
        name: 'sparklineWeek',
        label: 'Chart (Week)',
        frozen: false,
        hidden: true,
        classes: ['static'],
        id: Math.random(),
    },
    {
        name: 'sparklineMonth',
        label: 'Chart (Month)',
        frozen: false,
        hidden: true,
        classes: ['static'],
        id: Math.random(),
    },
    {
        name: 'buySentiment',
        label: 'Winner Sentiment',
        frozen: false,
        hidden: false,
        id: Math.random(),
    },
    {
        name: 'candleStickGraphDay',
        label: 'Hi/Lo (Day)',
        frozen: false,
        hidden: false,
        classes: ['static', 'candle'],
        id: Math.random(),
    },
    {
        name: 'candleStickGraphWeek',
        label: 'Hi/Lo (Week)',
        frozen: false,
        hidden: true,
        classes: ['static', 'candle'],
        id: Math.random(),
    },
    {
        name: 'candleStickGraphMonth',
        label: 'Hi/Lo (Month)',
        frozen: false,
        hidden: true,
        classes: ['static', 'candle'],
        id: Math.random(),
    },
    {name: 'aroon', label: 'Aroon', frozen: false, hidden: true, id: Math.random()},
    {name: 'atr', label: 'Avarage True Range', frozen: false, hidden: true, id: Math.random()},
    {name: '%B', label: 'Bollinger %B', frozen: false, hidden: true, id: Math.random()},
    {name: 'chaikin', label: 'Chaikin Volatility', frozen: false, hidden: true, id: Math.random()},
    {name: 'cci', label: 'Commodity Channel Index', frozen: false, hidden: true, id: Math.random()},
    {name: 'dm', label: 'Directional Movement', frozen: false, hidden: true, id: Math.random()},
    {name: 'ichimoku', label: 'Ichimoku', frozen: false, hidden: true, id: Math.random()},
    {name: 'KDJ', label: 'KDJ', frozen: false, hidden: true, id: Math.random()},
    {name: 'MACD', label: 'MACD', frozen: false, hidden: true, id: Math.random()},
    {name: 'momentum', label: 'Momentum', frozen: false, hidden: true, id: Math.random()},
    {name: 'pivot', label: 'Pivot Point', frozen: false, hidden: true, id: Math.random()},
    {name: 'sd', label: 'Standard Deviation', frozen: false, hidden: true, id: Math.random()},
    {name: 'vol', label: 'Volume', frozen: false, hidden: true, id: Math.random()},
    {name: '%R', label: 'Williams %R', frozen: false, hidden: true, id: Math.random()},
];

export default defaultColumns;
