import {Column} from "./Column";

const defaultColumns: Column[] = [                                                    // determines order of columns
    {
        name: 'instrumentName',
        label: 'Market',
        frozen: true,
        hidden: false,
        id: Math.random(),
    },
    {
        name: 'quickTrade',
        label: 'Trade',
        frozen: true,
        hidden: false,
        id: Math.random(),
    },
    {
        name: 'changeDay',
        label: 'Change (day)',
        frozen: true,
        hidden: false,
        id: Math.random(),
    },
    {
        name: 'changeWeek',
        label: 'Change (Week)',
        frozen: true,
        hidden: true,
        classes: ['thin'],
        id: Math.random(),
    },
    {
        name: 'changeMonth',
        label: 'Change (Month)',
        frozen: true,
        hidden: true,
        classes: ['thin'],
        id: Math.random(),
    },
    {
        name: 'rsi',
        label: 'RSI',
        frozen: false,
        hidden: false,
        classes: ['rsi'],
        id: Math.random(),
    },
    {
        name: 'positions',
        label: 'Positions',
        frozen: false,
        hidden: false,
        id: Math.random(),
    },
    {
        name: 'sparklineDay',
        label: 'Chart (Day)',
        frozen: false,
        hidden: false,
        classes: ['static'],
        id: Math.random(),
    },
    {
        name: 'sparklineWeek',
        label: 'Chart (Week)',
        frozen: false,
        hidden: true,
        classes: ['static'],
        id: Math.random(),
    },
    {
        name: 'sparklineMonth',
        label: 'Chart (Month)',
        frozen: false,
        hidden: true,
        classes: ['static'],
        id: Math.random(),
    },
    {
        name: 'buySentiment',
        label: 'Winner Sentiment',
        frozen: false,
        hidden: false,
        id: Math.random(),
    },
    {
        name: 'candleStickGraphDay',
        label: 'Hi/Lo (Day)',
        frozen: false,
        hidden: false,
        classes: ['static', 'candle'],
        id: Math.random(),
    },
    {
        name: 'candleStickGraphWeek',
        label: 'Hi/Lo (Week)',
        frozen: false,
        hidden: true,
        classes: ['static', 'candle'],
        id: Math.random(),
    },
    {
        name: 'candleStickGraphMonth',
        label: 'Hi/Lo (Month)',
        frozen: false,
        hidden: true,
        classes: ['static', 'candle'],
        id: Math.random(),
    },
];

export default defaultColumns;
